### ISSUE TITLE
Title: Prebuilt  info and html pages for ein?

### ISSUE THREAD

**Issue by tvraman** [dickmao/emacs-ipython-notebook#77]
Trying to build these on  git @HEAD fails badly for me. The
installation from melpa  sadly comes with no prebuilt docs, could the
next melpa push include prebuilt info files?

**Comment by dickmao** [comment]
By "build," are you referring to `make` in the `doc` subdirectory?

The documentation therein is severely outdated, and the Makefile has not been updated since 2015.  In short, the `doc` subdirectory is trash.

I have made good efforts to put all the relevant user information in the `README.rst`.  It really does contain 90% of what a prospective EIN user needs to know.

**Comment by tvraman** [comment]
thanks for the quick response. I was indeed trying to do make in the
docs directory.

Will use the rst files.

I think it would still be nice for the melpa install to come with some
docs, perhaps even the rst file.

**Comment by dickmao** [comment]
I don't believe including documentation in the manifest is customary practice.

**Comment by tvraman** [comment]
It's a good custom to introduce -- quite a few packages do it now. As
things stand one has to hunt all over github and fall into many tarpits
as I have:-)

Your previous message said look at the rst file, so I hopefully did  a
find for *.rst in my git checkout of your dev branch, and promptly fell
into another hole as you saw with the issue I filed re ein-subpackages,
and yes, you are correct, it was indeed buried in the docs/source directory.
--
